### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Compress_to_fit)
add_subdirectory(Compress_to_fitContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Compress_to_fitplugin
    Compress_to_fitContentplugin
    QtQuickDesignerComponents)