Compress-to-fit: alg::Rabin Class Reference
alg::Rabin Class Reference
module models
This class enables fast string matching. Makes use of two chained arrays. This class is intertwined with LZ77 and should not be used as separate entity. This class shall not modify the Window given.
Public Member Functions
Rabin (const Window &data, uint32_t pos, CompPreset preset)
Rabin & operator= (const Rabin &)=delete
void roll_hash (uint32_t num_of_rolls=1) noexcept
Roll and add the hash to the symbol_positions.
Token find_pattern ()
Find the biggest pattern between the look ahead buffer and search buffer.
auto get_pos () const noexcept
Static Private Member Functions
static auto bucket_index (uint32_t const hash_) noexcept -> uint32_t
static auto prev_bucket_index (uint32_t const hash_) noexcept -> uint32_t
static auto get_max_chain_from_preset (CompPreset const preset) noexcept -> size_t
Private Attributes
const Window & data
uint32_t hash = 0
uint32_t position
int32_t poss_table [MAX_HASH_SIZE]
int32_t prev_poss_table [MAX_WINDOW_SIZE]
const size_t MAX_CHAIN
Detailed Description
This class enables fast string matching. Makes use of two chained arrays. This class is intertwined with LZ77 and should not be used as separate entity. This class shall not modify the Window given.
Definition at line 201 of file lz77.cppm.
Constructor & Destructor Documentation
Rabin()
alg::Rabin::Rabin (const Window & data, uint32_t pos, CompPreset preset) inline
Precondition
data.max_size() > MAX_HASH_SIZE
Definition at line 208 of file lz77.cppm.
References data, Window::get_data(), MAX_CHAIN, alg::MIN_MATCH, and Rabin().
Referenced by Rabin().
Member Function Documentation
bucket_index()
auto alg::Rabin::bucket_index (uint32_t const hash_) -> uint32_t inline static nodiscard private noexcept
Definition at line 260 of file lz77.cppm.
References MAX_HASH_SIZE.
find_pattern()
Token alg::Rabin::find_pattern ()
Find the biggest pattern between the look ahead buffer and search buffer.
Definition at line 24 of file lz77_impl.cpp.
get_max_chain_from_preset()
auto alg::Rabin::get_max_chain_from_preset (CompPreset const preset) -> size_t inline static nodiscard private noexcept
Definition at line 284 of file lz77.cppm.
get_pos()
auto alg::Rabin::get_pos () const inline nodiscard noexcept
Definition at line 247 of file lz77.cppm.
operator=()
Rabin & alg::Rabin::operator= (const Rabin &) delete
prev_bucket_index()
auto alg::Rabin::prev_bucket_index (uint32_t const hash_) -> uint32_t inline static nodiscard private noexcept
Definition at line 272 of file lz77.cppm.
References MAX_WINDOW_SIZE.
roll_hash()
void alg::Rabin::roll_hash (uint32_t num_of_rolls = 1) noexcept
Roll and add the hash to the symbol_positions.
This function will check if position has reached the end
Warning
The position will be increased. THE WINDOW WILL NOT SLIDE
Parameters
num_of_rolls How many times it should roll, defaults to 1
find_pattern checks poss_table for a pattern match, if found it will keep searching down the chain of previous poss_table entries, which have been saved in prev_poss_table by roll_hash. This is repeated a MAX_CHAIN amount of times.
Definition at line 5 of file lz77_impl.cpp.
Member Data Documentation
data
const Window& alg::Rabin::data private
Definition at line 253 of file lz77.cppm.
Referenced by Rabin().
hash
uint32_t alg::Rabin::hash = 0 private
Definition at line 254 of file lz77.cppm.
MAX_CHAIN
const size_t alg::Rabin::MAX_CHAIN private
Definition at line 258 of file lz77.cppm.
Referenced by Rabin().
position
uint32_t alg::Rabin::position private
Definition at line 255 of file lz77.cppm.
poss_table
int32_t alg::Rabin::poss_table[MAX_HASH_SIZE] private
Definition at line 256 of file lz77.cppm.
prev_poss_table
int32_t alg::Rabin::prev_poss_table[MAX_WINDOW_SIZE] private
Definition at line 257 of file lz77.cppm.
The documentation for this class was generated from the following files:
Compress-to-fit/src/models/LZ77/lz77.cppm
Compress-to-fit/src/models/LZ77/lz77_impl.cpp