Compress-to-fit: LZ77ConcurrentCompressor Class Reference
LZ77ConcurrentCompressor Class Reference export
module models
Public Member Functions
LZ77ConcurrentCompressor (std::span< std::byte const > const data, size_t const concurrency, File &file, CompPreset const preset) noexcept(false)
~LZ77ConcurrentCompressor ()
void compress () noexcept(false)
Run the compression.
Private Member Functions
void check_results ()
Private Attributes
CompPreset const preset_
size_t const concurrency_
std::span< std::byte const > const data_ {}
std::vector< std::future< void > > results {}
size_t n_blocks_ {}
size_t n_completed_blocks {}
ConcOrderedFileList< LZ77Block > file_list_
ThreadPool thread_pool {}
Detailed Description
Definition at line 427 of file lz77.cppm.
Constructor & Destructor Documentation
LZ77ConcurrentCompressor()
LZ77ConcurrentCompressor::LZ77ConcurrentCompressor (std::span< std::byte const > const data, size_t const concurrency, File & file, CompPreset const preset) inline
Definition at line 430 of file lz77.cppm.
References LZ77ConcurrentCompressor(), and n_blocks_.
Referenced by LZ77ConcurrentCompressor().
~LZ77ConcurrentCompressor()
LZ77ConcurrentCompressor::~LZ77ConcurrentCompressor () inline
Definition at line 440 of file lz77.cppm.
Member Function Documentation
check_results()
void LZ77ConcurrentCompressor::check_results () inline private
Definition at line 495 of file lz77.cppm.
Referenced by compress().
compress()
void LZ77ConcurrentCompressor::compress () inline
Run the compression.
Definition at line 451 of file lz77.cppm.
References check_results(), n_blocks_, and n_completed_blocks.
Member Data Documentation
concurrency_
size_t const LZ77ConcurrentCompressor::concurrency_ private
Definition at line 485 of file lz77.cppm.
data_
std::span<std::byte const> const LZ77ConcurrentCompressor::data_ {} private
Definition at line 486 of file lz77.cppm.
file_list_
ConcOrderedFileList<LZ77Block> LZ77ConcurrentCompressor::file_list_ private
Definition at line 491 of file lz77.cppm.
n_blocks_
size_t LZ77ConcurrentCompressor::n_blocks_ {} private
Definition at line 488 of file lz77.cppm.
Referenced by compress(), and LZ77ConcurrentCompressor().
n_completed_blocks
size_t LZ77ConcurrentCompressor::n_completed_blocks {} private
Definition at line 489 of file lz77.cppm.
Referenced by compress().
preset_
CompPreset const LZ77ConcurrentCompressor::preset_ private
Definition at line 484 of file lz77.cppm.
results
std::vector<std::future<void> > LZ77ConcurrentCompressor::results {} private
Definition at line 487 of file lz77.cppm.
thread_pool
ThreadPool LZ77ConcurrentCompressor::thread_pool {} private
Definition at line 492 of file lz77.cppm.
The documentation for this class was generated from the following file:
Compress-to-fit/src/models/LZ77/lz77.cppm