Compress-to-fit: ConcFileBuffer< T > Class Template Reference
ConcFileBuffer< T > Class Template Reference export
module containers
Ring queue-like where if size > capacity, the oldest elements are written to stream. At least the most recent minimum_size_ number of elements shall be available for reading.
Public Member Functions
ConcFileBuffer (File &out_stream, size_t const minimum_size)
~ConcFileBuffer ()
constexpr void push (T const &value)
constexpr void push (T &&value)
template<std::ranges::range R>
constexpr void append_range (R &&rg)
Appends a range to the container.
constexpr void reserve (size_t new_capacity) noexcept(false)
Increase capacity to at least #new_capacity.
constexpr auto operator[] (size_t index) const -> T
constexpr size_t capacity () const noexcept
constexpr size_t minimum_size () const noexcept
void set_minimum_size (size_t const new_minimum_size) noexcept
Set a new minimum size. A value less than minimum_size will be ignored.
Private Member Functions
auto constexpr write_buffer () noexcept(false)
Writes elements outside the minimum range.
constexpr size_t true_index () const noexcept
Private Attributes
File & out_stream_
T * data_
std::allocator< T > allocator
std::shared_mutex mut
size_t index_ = 0
size_t written_index_ = 0
size_t capacity_ = 0
size_t minimum_size_ = 0
Detailed Description
template<SerializableToDisk T>
class ConcFileBuffer< T >
Ring queue-like where if size > capacity, the oldest elements are written to stream. At least the most recent minimum_size_ number of elements shall be available for reading.
Template Parameters
T type stored, must be trivially copyable
Definition at line 17 of file file_buffer.cppm.
Constructor & Destructor Documentation
ConcFileBuffer()
template<SerializableToDisk T> ConcFileBuffer< T >::ConcFileBuffer (File & out_stream, size_t const minimum_size) inline
Definition at line 21 of file file_buffer.cppm.
~ConcFileBuffer()
template<SerializableToDisk T> ConcFileBuffer< T >::~ConcFileBuffer () inline
Definition at line 27 of file file_buffer.cppm.
Member Function Documentation
append_range()
template<SerializableToDisk T> template<std::ranges::range R> void ConcFileBuffer< T >::append_range (R && rg) inline constexpr
Appends a range to the container.
Parameters
rg range to append
Precondition
index_ > minimum_size_
Definition at line 71 of file file_buffer.cppm.
capacity()
template<SerializableToDisk T> size_t ConcFileBuffer< T >::capacity () const inline constexpr noexcept
Definition at line 139 of file file_buffer.cppm.
minimum_size()
template<SerializableToDisk T> size_t ConcFileBuffer< T >::minimum_size () const inline constexpr noexcept
Definition at line 140 of file file_buffer.cppm.
operator[]()
template<SerializableToDisk T> auto ConcFileBuffer< T >::operator[] (size_t index) const -> T inline constexpr
Definition at line 125 of file file_buffer.cppm.
push() [1/2]
template<SerializableToDisk T> void ConcFileBuffer< T >::push (T && value) inline constexpr
Parameters
value
Precondition
index_ > minimum_size_
Definition at line 54 of file file_buffer.cppm.
References index_, and write_buffer().
push() [2/2]
template<SerializableToDisk T> void ConcFileBuffer< T >::push (T const & value) inline constexpr
Parameters
value
Precondition
index_ > minimum_size_
Definition at line 39 of file file_buffer.cppm.
References index_, and write_buffer().
reserve()
template<SerializableToDisk T> void ConcFileBuffer< T >::reserve (size_t new_capacity) inline constexpr
Increase capacity to at least #new_capacity.
Parameters
new_capacity New capacity of the buffer
Definition at line 93 of file file_buffer.cppm.
set_minimum_size()
template<SerializableToDisk T> void ConcFileBuffer< T >::set_minimum_size (size_t const new_minimum_size) inline noexcept
Set a new minimum size. A value less than minimum_size will be ignored.
Parameters
new_minimum_size New minimum size, shall be at least minimum_size big
Definition at line 148 of file file_buffer.cppm.
true_index()
template<SerializableToDisk T> size_t ConcFileBuffer< T >::true_index () const inline nodiscard constexpr private noexcept
Definition at line 197 of file file_buffer.cppm.
References capacity_, and index_.
write_buffer()
template<SerializableToDisk T> auto constexpr ConcFileBuffer< T >::write_buffer () inline constexpr private
Writes elements outside the minimum range.
Precondition
lock MUST be locked with #lock
Definition at line 169 of file file_buffer.cppm.
References capacity_, index_, minimum_size_, and written_index_.
Referenced by push(), and push().
Member Data Documentation
allocator
template<SerializableToDisk T> std::allocator<T> ConcFileBuffer< T >::allocator private
Definition at line 158 of file file_buffer.cppm.
capacity_
template<SerializableToDisk T> size_t ConcFileBuffer< T >::capacity_ = 0 private
Definition at line 162 of file file_buffer.cppm.
Referenced by true_index(), and write_buffer().
data_
template<SerializableToDisk T> T* ConcFileBuffer< T >::data_ private
Definition at line 157 of file file_buffer.cppm.
index_
template<SerializableToDisk T> size_t ConcFileBuffer< T >::index_ = 0 private
Definition at line 160 of file file_buffer.cppm.
Referenced by push(), push(), true_index(), and write_buffer().
minimum_size_
template<SerializableToDisk T> size_t ConcFileBuffer< T >::minimum_size_ = 0 private
Definition at line 163 of file file_buffer.cppm.
Referenced by write_buffer().
mut
template<SerializableToDisk T> std::shared_mutex ConcFileBuffer< T >::mut mutable private
Definition at line 159 of file file_buffer.cppm.
out_stream_
template<SerializableToDisk T> File& ConcFileBuffer< T >::out_stream_ private
Definition at line 156 of file file_buffer.cppm.
written_index_
template<SerializableToDisk T> size_t ConcFileBuffer< T >::written_index_ = 0 private
Definition at line 161 of file file_buffer.cppm.
Referenced by write_buffer().
The documentation for this class was generated from the following file:
Compress-to-fit/src/util/containers/file_buffer.cppm